services:
  - type: web
    name: aquaguru
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_ENGINE
        value: auto
      - key: PYTHON_VERSION
        value: 3.11.9
